### ISSUE TITLE
Score match event points ('share your ranking')

### ISSUE THREAD

**Issue by joseph98** [SchoolIdolTomodachi/SchoolIdolAPI#107]
For 'share my ranking' on score match events, some users use 'points' field for event points, others for song rank points, which makes the rankings list inconsistent.  

Possible resolutions: 
-change field ordering and label so its more obvious that field is referring to event points -or-
-add separate field for 'song rank points' for 'score match' events

![score-match-points](https://cloud.githubusercontent.com/assets/2871658/6925713/839bb092-d79e-11e4-8e5e-0ea94d06af2d.gif)
![share-ranking](https://cloud.githubusercontent.com/assets/2871658/6925853/a5c66e7c-d79f-11e4-8170-57660f44cb55.gif)

**Comment by db0company** [comment]
Thanks for reporting! We will fix this asap.
