### ISSUE TITLE
Put verified accounts on top

### ISSUE THREAD

**Issue by Praeliator** [SchoolIdolTomodachi/SchoolIdolAPI#108]
When we click on the 'Players' tab on top, there'll be players with top ranks on top and scrolling down for players with ranks getting lower. I think that anyone with verified accounts should go on the very top of the list. Or implement into the 'Search Players' space an option to search for verified accounts.

**Comment by db0company** [comment]
That's a good idea :)
Here it is:
http://schoolido.lu/users/?term=&ordering=-accounts_set__verified
