### ISSUE TITLE
Two same accounts appearing on verified at the same time

### ISSUE THREAD

**Issue by Praeliator** [SchoolIdolTomodachi/SchoolIdolAPI#109]
Some verified accounts appear twice at the same time, dunno if this was intentional or a bug.
![asdad](https://cloud.githubusercontent.com/assets/11804155/6996867/244e0b54-dbd5-11e4-82ac-9b9a27bb4ff8.png)

**Comment by db0company** [comment]
Thanks for reporting~
It's actually on purpose, since we order by rank, if you have multiple account, you appear in the ranking where your account should be.
