### ISSUE TITLE
Filter and sort players by game region

### ISSUE THREAD

**Issue by yaycupcake** [SchoolIdolTomodachi/SchoolIdolAPI#110]
For example, sorting people who play EN (either exclusively or along with JP), and if you're going by rank, sort them by their EN rank, not their JP rank (if that's higher). And same for JP. Probably not super important but I think it'd be nice to be able to sort only EN players by their EN accounts, or the same for JP.

**Comment by db0company** [comment]
Thanks for suggesting!
I don't really know if that's doable and how hard it will be, but I'll see what I can do :)
