### ISSUE TITLE
API: allow direct access to an event by event number

### ISSUE THREAD

**Issue by martirsadota** [SchoolIdolTomodachi/SchoolIdolAPI#111]
...so if I go to, say, `/api/events/?id=1` (or similar) I'd get data about just the first event, and so on.

In addition, it would also be nice to have an API short-cut to the current event (something like `/api/events/?current=(en|jp)`).

**Comment by db0company** [comment]
You can already `GET /api/events/1` but since the numbers don't really make sense I didn't write it in the documentation. Feel free to use it if it's useful for you~

I'll see what I can do for the current :)

**Comment by db0company** [comment]
@martirsadota You probably saw it already, but we changed the urls and now you can access a single event using the name of the event, such as: http://schoolido.lu/api/events/%E6%9C%88%E3%81%BE%E3%81%A7%E6%8A%B1%E3%81%84%E3%81%A6%20Love%2AHeart/

Tell me if it works for you!
