### ISSUE TITLE
Cards: Hide "Skill (Level)" field for "skill-less" cards (e.g. Ns)

### ISSUE THREAD

**Issue by martirsadota** [SchoolIdolTomodachi/SchoolIdolAPI#116]
![image](https://cloud.githubusercontent.com/assets/8792260/7270789/40f47362-e911-11e4-9ae5-5d5cb97e5b9a.png)

...of course the skill level field is pointless in this case.

**Comment by Engil** [comment]
Thank you for reporting, this should be fixed
