### ISSUE TITLE
"Tumblr account" section does not support long usernames

### ISSUE THREAD

**Issue by ccrowles** [SchoolIdolTomodachi/SchoolIdolAPI#126]
I wanted to add my tumblr in the appropriate section, but then I found out that my username (NOT url) was 21 characters, exactly 1 longer than the maximum you allow. Considering also that the maximum for a username on tumblr is 32 characters, it might be wise to reconsider the maximum of characters you allow, because the whole "tumblr" section is kinda pointless otherwise...

Thanks.

**Comment by db0company** [comment]
I updated the limits for the social links: https://github.com/SchoolIdolTomodachi/SchoolIdolAPI/commit/5ccc145f734e7557c65d08cf0c3140ee0438f46f
Thanks for reporting!
