### ISSUE TITLE
I can't remember any of my infos !

### ISSUE THREAD

**Issue by UtsukushiSH** [SchoolIdolTomodachi/SchoolIdolAPI#129]
I now use Firefox and I have to enter all of my codes again but I can't remember any of them, since they were just automaticaly put in by Google Chrome. Could you send me back my infos please ? My email is abigail06283@gmail.com (I'm sure that my name have "Utsukushi" in it but maybe it has "SH" at the end) Thank you very much !

**Comment by db0company** [comment]
Hi,

To make sure you're the owner of the profile, can you send us an email to contact@schoolido.lu from the email associated with your profile? We will reset your password for you.

Thanks!
