### ISSUE TITLE
Make searching for idols not case sensitive.

### ISSUE THREAD

**Issue by inflictedknight** [SchoolIdolTomodachi/SchoolIdolAPI#133]
This is a little minor, but I thought it would be a good idea to make searching for idols not case sensitive. As it is right now, if you search for idols with all lowercase letters, it won't bring back any results:

http://schoolido.lu/cards/?search=kotori&name=&rarity=&attribute=&skill=&collection=&is_promo=&is_special=&is_event=&is_world=on&account=&ordering=id&reverse_order=on

**Comment by db0company** [comment]
This should be fixed now, thank you!
