### ISSUE TITLE
Incorrect skill names of promo cards

### ISSUE THREAD

**Issue by msmrrenda** [SchoolIdolTomodachi/SchoolIdolAPI#134]
Japanese skill names and effects of some promo cards are wrong.
e.g. http://schoolido.lu/cards/492/
"初めての手作りチョコ" is wrong, "リズミカルエール (Rhythmical Yell) " is correct.

**Comment by Engil** [comment]
Should be fixed now!
Thank your for reporting this.
Cheers,
