### ISSUE TITLE
Suggestion: Options & Icon

### ISSUE THREAD

**Issue by nikochi** [SchoolIdolTomodachi/SchoolIdolAPI#145]
I'm glad that now we can view cards based on sub-catagories. (bibi, 1st year, etc) however the icon
somehow confuseing, especially on the rarity and attributes option, it'd be better if the options are like before when we click we see the options and pick from it., instead of the icons. it's hard to see which is the one that the turn on.  i think the previous one is better cause it's simpler and easier to see.
i kinda wish it'd changed back to previous looks.

**Comment by ceratopian** [comment]
Would it be possible to implement as a "style" or "view" type to allow the user to choose? Some people are more text-oriented while others are more visual-oriented.

**Comment by nikochi** [comment]
that'd be awesome if it's possible to be implemented. =)
oh and i just realized now we cant really see the stats/skill of a card when we click it.
it redirected us to a specific page, unlike before it just like expanded and stayed in the same page. i prefer the previous =(
