### ISSUE TITLE
Cannot edit card

### ISSUE THREAD

**Issue by MikuAuahDark** [SchoolIdolTomodachi/SchoolIdolAPI#156]
So, I want to edit my card(#410) from Idolized, Max Bonded to Idolized, Max Bonded, and Max Leveled. But everytime I click the edit card button, there's no popup to edit the card info.

Tired full reloading the page, still same.

**Comment by db0company** [comment]
What's your browser? Can you open the javascript console and tell me what you see? https://developer.chrome.com/devtools/docs/console#opening-the-console

**Comment by MikuAuahDark** [comment]
I use Mozilla Firefox 38. When I open Developer Console yesterday, I see some javascript errors. Not sure for the exact error because I can't access the site this time(gives me Bad Request :confused: )

**Comment by MikuAuahDark** [comment]
It seems that I can't edit my card info from the card page itself(example: I can't edit my card info from [here](http://schoolido.lu/cards/410/)) but I can edit my card info from /cards/ page(and display all of my cards from there).

**Comment by MikuAuahDark** [comment]
Okay previously everything working fine (I believe it working fine in October) but I can't edit the card info again, both from the /cards/ page and from the /cards/<number>/ page.
