### ISSUE TITLE
Allow ordering cards in /cards/ the same way cards are ordered in profile decks

### ISSUE THREAD

**Issue by ceratopian** [SchoolIdolTomodachi/SchoolIdolAPI#158]
To keep tabs on what's changed, I usually have to go to my profile (since cards are listed by rarity) then open a card that way. It'd be easier if I could just go to cards view, select my account and have the cards sorted by rarity.

**Comment by MikuAuahDark** [comment]
The cards already sorted by rarity

**Comment by ceratopian** [comment]
Not in Cards view. http://i.imgur.com/g8GTvOn.png

**Comment by MikuAuahDark** [comment]
> if I could just go to cards view, select my account and have the cards sorted by rarity.

I think I need some sleep. Sorry, didn't notice that

**Comment by ceratopian** [comment]
Np. It's definitely more of an wishlist item than a fix that needs to be implemented.

**Comment by db0company** [comment]
We can add that, yep. Thanks for your suggestion!

**Comment by MikuAuahDark** [comment]
It's possible to sort cards by rarity.

Use this link: `http://schoolido.lu/cards/?account=<account id>&stored=Deck&ordering=rarity&reverse_order=on`

replace `<account id>` with your Account ID found in your profile.

Locating Account ID is bit tricky. Click your username in the top bar and **hover** your cursor to your account. The link will be something like this: `http://schoolido.lu/user/<username>/#<account id>`

[Here's a screenshot showing card list sorted by rarity](http://imgur.com/ZydJkOf)

**Comment by ceratopian** [comment]
I tried your workaround and it's almost but [not quite](http://i.imgur.com/ijPCnDr.jpg). It seems to be sorting by card number within rarity.

It would be easier if it was sorted the way the profile is sorted. As it is now even with the workaround, it's still easier for me to look at the profile account to see if I need to change any card, right click/open new tab each card I need change, and update it that way.

Easiest would be sort by rarity in cards view the way the profile is sorted (if it gets implemented) since - as it is noted on profile view - we should go to cards view to actually update the cards.
