### ISSUE TITLE
[Request] Bulk edit multiple cards

### ISSUE THREAD

**Issue by dgw** [SchoolIdolTomodachi/SchoolIdolAPI#159]
Especially when first filling in one's album and current deck at higher levels (100+ cards in deck alone), it would be a huge time-saver to be able to just quickly add a bunch of cards, then select groups of them to set the status (storage, idolized/max level/max bond) in bulk. I'm doing the initial fill of my profile right now and it's very tedious to edit each card manually, and it takes a lot of time waiting for modal dialogs to open and close too.

**Comment by db0company** [comment]
Sorry about the delay!

After your suggestion as well as other people asking for it on Twitter and Reddit, we implemented the album builder: http://schoolido.lu/cards/albumbuilder/

To learn how it works, here's a guide: https://www.youtube.com/watch?v=BuYsz8-yQgI
