### ISSUE TITLE
[Feature] Status/Update Log? | Future: Upload screenshots?

### ISSUE THREAD

**Issue by ceratopian** [SchoolIdolTomodachi/SchoolIdolAPI#160]
Edit: This is all future stuff, not bug stuff. Just some ideas. I hope that's ok!

I've been editing my profile for this but I think it would be nice to have a Status/Update log feature. Something short like twitter (or longer) with editable datestamp. Maybe with tags to account (multiple selectable) so it shows up on the Activities tab?

Also cool but probably more difficult/size-hogging would be the ability to upload pictures attached the status log. (Show off 10 +1's for instance.)

Even cooler but waaaaay future stuff, would be to able to upload screenshots, get some sort of recognition logic and auto-add the cards to the tagged account?

Edit2: omg I just realized you actually did some of this! * o * It would still be nice to be able to "comment" a new entry into the activities tab. ('ω')

**Comment by db0company** [comment]
Hi! We actually implemented all that after your suggestion, but I just realized that I never actually replied to you >_<

Thank you so much for this and I hope you enjoy these features!
