### ISSUE TITLE
Sort order of support member cards (teachers, etc.) is wrong; their rarity value (number of stars) seems to have changed

### ISSUE THREAD

**Issue by dburr** [SchoolIdolTomodachi/SchoolIdolAPI#165]
I noticed something odd when updating my cards today, the two support member cards (teachers, etc.) that I have in my deck are sorted wrong. It used to be that if I sort my member list by Rarity in the game, I could do a 1-for-1 comparison between the cards as displayed in game, vs. the cards as displayed on my School Idol Tomodachi account. Now this is no longer the case. I think this seems to be due to a change that KLab made recently in-game, as I remember updating my cards right before the just-ended Catgirl Rin event, and the sort order in-game was the same as on my Tomodachi account (and I also had teacher/alpaca cards in my deck at that time.)

Some screenshots:
* <A HREF="https://dl.dropboxusercontent.com/u/169813/IMG_1636.JPG" target="_blank">Game</A>
* <A HREF="https://dl.dropboxusercontent.com/u/169813/IMG_1637.JPG" target="_blank">School Idol Tomodachi</A>

As you can see I currently have two support cards in my deck (Cocoa Yazawa and Nanako Yamauchi). In the game screenshots, they appear at the very end of my block of R cards, just before the N cards. However in the School Idol Tomodachi screenshots, they show up in the middle of all the other R cards.

It appears the game now considers (at least some) support cards "less rare" than they used to be. In game, they appear with 3 stars; on Tomodachi they appear with 4 stars. Unfortunately I don't have any SR/UR support cards, so I can't say if the rarity value of those has changed as well. I'm guessing that fixing this should be a fairly simple database update.

**Comment by dburr** [comment]
I just scouted an SR Assist card ([#383 Mika](http://schoolido.lu/cards/383/)) and it too is sorted in a different order in both the game and on Tomodachi. On Tomidachi the card appears as a "6-star" card and appears in the middle of my block of SR's; however, in the game it is only shown as a "5-star" card and is sorted more towards the rear of my SR's. So yeah, it looks like all of the Assist cards may have recently been "demoted" in rarity value by the game.

**Comment by dburr** [comment]
Updating this ticket, because it looks like this has been at least partially fixed. I have a teacher card (#148  笹原京子 Sasahara Kyouko) in my deck as an event reward from the just-ended Kotori score match, and it is now sorted properly on Tomodachi. Unfortunately I already trained my alpaca without thinking to check its sort order, and I don't have any SR/UR support cards so I can't check those either.

**Comment by db0company** [comment]
Special cards used to be automatically idolized, because that's the way we store cards images (so you know ALL cards have an idolized image). I changed that, now special cards are never idolized and promo cards are always idolized. I also changed the edit forms so it's not possible to change idolization of special and promo cards.
