### ISSUE TITLE
Images Temporarily Unavailable

### ISSUE THREAD

**Issue by LindsayL** [SchoolIdolTomodachi/SchoolIdolAPI#168]
No images have been shown for the cards the past couple days. 

I have tried in IE10 and chrome.  Cleared caches, no luck. :/

**Comment by dburr** [comment]
There is a workaround available [here](http://kach.olympe.in/llsif/sitfix.php) which, while not perfect, will at least make the site usable again.

**Comment by LindsayL** [comment]
Thank you for the work around!  It was very helpful. :D
