### ISSUE TITLE
More flexible card search parameters

### ISSUE THREAD

**Issue by dreamsicl** [SchoolIdolTomodachi/SchoolIdolAPI#175]
Right now, we can only search only one card rarity at a time. (Only N's if we click N, only R's if we click R, etc.) I'd like to be able to specify a search for R + SR + UR cards, of a specific property, so that I can see what cards are in what limited scouting boxes at a time. (All the cards I can get from the Smile box, for example.) 

I'd also like some English translation of the Collections parameter. (I looked, but couldn't find any documentation of it.) Being able to select multiple collections would be useful too, for the purpose of looking at scouting boxes.

**Comment by Engil** [comment]
Thank you for your suggestion, however it would imply a lot of work for us and would force us to change basically everything in the code, so we think the feature is not worth the effort.
Cheers,
