### ISSUE TITLE
Feature request: add card skill type icon when hovering over cards in profile screen

### ISSUE THREAD

**Issue by dburr** [SchoolIdolTomodachi/SchoolIdolAPI#177]
It would be handy if you could add the skill type icon (healer, PL, etc.) to the little display that pops up when you hover over a card in your profile screen. It would make identifying the particular type of card really easy, instead of having to click through to another screen. It would make it really easy to quickly pick out cards to build out a specific type of team, and would be especially useful with my JP account since I can't read the skill names/descriptions in the game.

**Comment by db0company** [comment]
I just added those shortcut buttons on your profile:
![screen shot 2015-12-11 at 4 07 08 pm](https://cloud.githubusercontent.com/assets/722281/11747065/8227a724-a021-11e5-9b15-72933250b676.png)

Does it work for you?

**Comment by dburr** [comment]
Actually I like the new buttons better than my idea. Thanks! :)

Donald
