### ISSUE TITLE
Problem adding a youtube channel to my profile

### ISSUE THREAD

**Issue by Plusmine** [SchoolIdolTomodachi/SchoolIdolAPI#182]
First of all, sorry if this isn't the place, or if this already has a solution.

I wanted to add my youtube account to my profile. 
It requests to write only my ID/username, but later I found that the web puts that id/name after a "https://www.youtube.com/user/[xxx]" url. 

My problem is that (if i'm not wrong) the newest accounts, as mine, instead of that order, they use a "https://www.youtube.com/c/[xxx]" url, from channel, so if you check the link from my profile it goes to nowhere, not my profile, because of that "/user/" and "/c/" difference.

Could be any option or solution to this?

**Comment by db0company** [comment]
Do you know if the old accounts also work with the second URL? In that case I can just replace the URL.

**Comment by YoannGo** [comment]
Maybe the option will be to have : "https://www.youtube.com/username", and youtube just use the correct url I think, I have two old accounts with "/user/", someone can confirm it work? ;-)

**Comment by Plusmine** [comment]
"Do you know if the old accounts also work with the second URL? In that case I can just replace the URL."
No, they don't. :/ It needs to be exactly the correct URL. I checked different famous and older channels and it must be /user/ tag in that case.

Maybe the only way to resolve this is allowing to paste the entire URL about Youtube, or having different options when you select the plataform in our settings (Youtube/c/ and Youtube/user/ or something like that), but I don't know.

Btw, thanks for answering. Loving the site.

**Comment by db0company** [comment]
I think the best solution that doesn't change the database too much is to have 2 different kind of links:
YouTube (created after <date>)
YouTube (older)

What do you think?

@Plusmine I'm glad you like it, thanks for using it :)

**Comment by Plusmine** [comment]
"""I think the best solution that doesn't change the database too much is to have 2 different kind of links:
YouTube (created after )
YouTube (older)

What do you think?"""
Perfect, too. If you can do that, it could work. 
I didn't think about it, and thanks!

**Comment by YoannGo** [comment]
I think the simpliest solution si to just enter our username number, it will be easier and take less place to database too, more benefits !

**Comment by Plusmine** [comment]
"In case of: I suggested the "https://www.youtube.com/username" for tthe database use, and it simply redirect, I don't find another way more easy than that IMHO. ^^"

I just tried this, and yep, it works too!
Thanks, YoannGo.
