### ISSUE TITLE
The "rooted apks" threat is outdated

### ISSUE THREAD

**Issue by ismakenji** [SchoolIdolTomodachi/SchoolIdolAPI#185]
Hi! I've noticed that the apk threat is outdated, so I've been searching and I found this page that has both jap and en version https://llsif.kawaiii.link/ 

I hope it helps!
![captura de pantalla 2016-01-06 14 14 04](https://cloud.githubusercontent.com/assets/16576310/12143311/c4bfe9ee-b47f-11e5-80dc-a80769a252a0.png)

**Comment by db0company** [comment]
Thanks for your suggestion, I updated the link!

**Comment by redemption024** [comment]
Aha! I've been wondering how my site ended up on schoolidolu. So this is it. Thanks folks ;)
