### ISSUE TITLE
Different levels

### ISSUE THREAD

**Issue by thhours** [SchoolIdolTomodachi/SchoolIdolAPI#192]
[Suggestion] Different levels of private profile, I have retrieve my account with KLab and the teams information played a big part as I could not remember any of my account creation details, It would be great if we could private our teams without having to private our profiles.

**Comment by Engil** [comment]
Thank you for your suggestion, however the only reason to store your teams in Sukutomo would be to show them to the community, otherwise I don't think there is any value to put them on your profile since you can just see them in game.
Cheers,
