### ISSUE TITLE
Missing Romaji Names for Songs

### ISSUE THREAD

**Issue by 765prorepo** [SchoolIdolTomodachi/SchoolIdolAPI#193]
Song data are fetched via the API `http://schoolido.lu/api/songs/`

Some of the songs do not have any Romaji or English name:

- 17 ラブノベルス (Love Novels)
- 50 ぶる~べりぃ♡とれいん (Blueberry Train)
- 57 スピカテリブル (SpicaTerrible)
- 66 小夜啼鳥恋詩 (Nightingale Love Song)
- 75 錯覚CROSSROADS (Sakkaku CROSSROADS)
- 80 ずるいよMagnetic today (Zurui yo Magnetic Today)

**Comment by db0company** [comment]
Thank you for reporting this. It should be fixed now!
