### ISSUE TITLE
How to retrieve cards by sub unit?

### ISSUE THREAD

**Issue by Kevin170113664** [SchoolIdolTomodachi/SchoolIdolAPI#248]
I am trying to get card filter by sub unit by the url:
```
http://schoolido.lu/api/cards/?japanese_name=高海 千歌,渡辺 曜,黒澤 ルビィ
```
but seems it does not respond anything.

Does anyone know how to retrieve cards by sub unit?

**Comment by db0company** [comment]
It's not possible to filter cards by idols' subunits, but I can totally add that if you want. It would be something like `?idol_sub_unit=AZALEA` for example.

It's also not possible now to filter using multiple idols, but I can also add them. Tell me what you prefer and what you'll use it for and I'll add that.

**Comment by Kevin170113664** [comment]
@db0company Wow, it's very kind of you.
Whether filtering by sub unit or using multiple idols is OK for me.
You can implement any of them.

**Comment by db0company** [comment]
I implemented both. You can see the new things with the documentation differences: https://github.com/SchoolIdolTomodachi/SchoolIdolAPI/wiki/API-Cards/_compare/d02da5a3db5dff3556b46298f336c445e99dafb4...5e61facd16e2c3af39580faff2dae7468dbe8873 and here's the commit: https://github.com/SchoolIdolTomodachi/SchoolIdolAPI/commit/9c32d6db377ed2b8fa56dc1a8f2315920be6f7d5
