### ISSUE TITLE
Wrong Skill Name on #796 Umi

### ISSUE THREAD

**Issue by sspacerace** [SchoolIdolTomodachi/SchoolIdolAPI#266]
Umi's skill here is listed as a Healer, but the skill description is of a Score Up. I accidentally added her to my Healer team as a result, lol ^.^ It would be nice to take care of this, though.

![screen shot 2016-10-29 at 10 40 53 pm](https://cloud.githubusercontent.com/assets/18728237/19834723/d0d58f34-9e28-11e6-871c-383237994de3.png)

**Comment by db0company** [comment]
She was actually a healer and the skill description was wrong, not the name, so she was in the right team :)

Thanks for reporting this!

![](https://pbs.twimg.com/media/CvFNcT-WcAAmoj7.jpg:large)
![](https://pbs.twimg.com/media/Cvje8MiW8AIYB9k.jpg:large)
