### ISSUE TITLE
Too many issues, please close them when they're cleared!

### ISSUE THREAD

**Issue by KasaiDot** [SchoolIdolTomodachi/SchoolIdolAPI#283]
### :warning: Too many issues, please close them when they're cleared ! :warning:

**Comment by db0company** [comment]
I close issues when I fix things. It's just that there are too many things to fix and I don't really have time to fix them.

**Comment by KasaiDot** [comment]
Need help for that?
If you're ok with me I can help you.

**Comment by JDShu** [comment]
+1 I've been wanting to contribute bugfixes to get acclimated to the codebase, but there are lots of issues in need of triaging or refer to bugs that have already been fixed. I'm also up for helping out here.
