### ISSUE TITLE
Filter OUT event cards?

### ISSUE THREAD

**Issue by yaycupcake** [SchoolIdolTomodachi/SchoolIdolAPI#44]
Can we sort cards so we can not only choose to see only event cards, but also have an option to view only NON-event cards? I guess same for promos... Basically, an option to see all cards, an option to see ONLY those kind of cards, and an option to see all cards EXCEPT those. That kind of feature would be really helpful, especially since you can't get promo cards in scouting, and event cards are a lot more rare in scouting. Being able to only view cards that aren't event cards and/or that aren't promo cards would be great. I suppose same could go for special cards, but there's a lot less of those.

**Comment by db0company** [comment]
Will do!
Thanks for suggesting this.
