### ISSUE TITLE
Use circled images instead of full cards on profile

### ISSUE THREAD

**Issue by db0company** [SchoolIdolTomodachi/SchoolIdolAPI#48]

**Comment by db0company** [comment]
This makes the pages very slow and heavy to load, so it's important.

**Comment by diethnis** [comment]
Are the circled images available anywhere from data dumps?

**Comment by db0company** [comment]
There's a `round_card_image` field in the API `cards` endpoint:

`GET http://schoolido.lu/api/cards/1/`

The images come from [this wiki](http://www59.atwiki.jp/lovelive-sif/) and they don't have all of them.
If you need a placeholder, you can use:
`http://schoolido.lu/static/circle-Pure.png` (with Smile, Pure, Cool or All)

**Comment by kjohn3** [comment]
Pretty minor but I thought the URs looked a lot better and more "special" when they had their original backgrounds and lighting. I'm assuming a theme selector isn't possible?
