### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by ahboy99** [SchoolIdolTomodachi/SchoolIdolAPI#52]
about guild's?

**Comment by db0company** [comment]
You mean "teams"?

![](https://lh3.googleusercontent.com/-mGiJAVehFhE/VPNlpLCpO2I/AAAAAAACXvw/d9T2GNPuSbY/w2781-h1565-no/2015-03-01.jpg)
This?

**Comment by ahboy99** [comment]
i know here for issue a bug but i wanted to suggest it for people create a group....

**Comment by db0company** [comment]
Thank you for your suggestion. We will add teams soon!
