### ISSUE TITLE
Event tiers without specific rank?

### ISSUE THREAD

**Issue by yaycupcake** [SchoolIdolTomodachi/SchoolIdolAPI#53]
I don't really keep track of the exact rank I was in any events but it'd be nice to at least say which tier you were in events on your profile.

**Comment by db0company** [comment]
Thanks for the suggestion.
However, I find this a bit messy. How would we add you in the global ranking? Should we display a different ranking? Should we consider you have the minimum points to be in the tier?
I'm a bit confused on how to implement that and show it properly.
